### ISSUE TITLE
Issue upload

### ISSUE THREAD

**Issue by jaderbavaresco** [mapilio/mapilio-kit#140]
### Question

How can I solve it?

PS C:\Users\jader\OneDrive\Área de Trabalho\mapilio-kit\docker> docker exec -it kit mapilio_kit upload OutputData/frames --geotag_source "gpx" --geotag_source_path "OutputData/metadata/gps_track.gpx"
metadata properties being processed: 100%|█████████████████████████████████████████| 434/434 [00:48<00:00,  8.97files/s]
usage: mapilio_kit [-h] [--version]
                   {upload,decompose,authenticate,video_upload,image_and_csv_upload,CSVprocessor,gopro360max_process,zip,run}
                   ...
mapilio_kit: error: '<' not supported between instances of 'datetime.datetime' and 'NoneType'
PS C:\Users\jader\OneDrive\Área de Trabalho\mapilio-kit\docker>

**Comment by gorkemgul** [comment]
Hi @jaderbavaresco, 

We dived into the problem and found the source. With this update, we've fixed the problem. Please feel free to try the process again and if you face with any kind of problem please report it as well.

Sincerely,
