### ISSUE TITLE
When will the desktop uploader released?

### ISSUE THREAD

**Issue by Byter3** [mapilio/mapilio-kit#149]
### Question

When will the desktop uploader released? I asked this via the contact us form as well weeks ago, but did not got an answer. I have a bunch of 360 videos I'll like to upload to Mapilio as well.

**Comment by jaderbavaresco** [comment]
It is very complicated to use PIP to send data for those who do not have an affinity with programming. It's a shame that they don't have desktop upload yet. I will need to delete my videos because I have no more space. I wish I could send it before deleting it.

**Comment by Byter3** [comment]
> It is very complicated to use PIP to send data for those who do not have an affinity with programming. It's a shame that they don't have desktop upload yet. I will need to delete my videos because I have no more space. I wish I could send it before deleting it.

Same here. I'm still holding up, but soon I'll have to delete some of them.

**Comment by gorkemgul** [comment]
Hi @Byter3, 

We've been working on Desktop Uploaders recently, and back with marvelous news! 

Our Linux Desktop Uploader released as beta, it's now available on Mapilio's website. To download it please visit: https://mapilio.com/uploader 

Windows, and Mac versions will be released soon, 

Sincerely,

**Comment by jaderbavaresco** [comment]
Hi - The download link is offline. Can you help me? 404 - page not found

https://github.com/mapilio/mapilio-kit/releases/download/v2.0.31/mapilio-kit--linux-x86_64

**Comment by gorkemgul** [comment]
Hi @jaderbavaresco, we're making improvements on releases, they will be back as soon as possible :tada:
