### ISSUE TITLE
Add support for sampling/processing but not uploading

### ISSUE THREAD

**Issue by Coehill** [mapilio/mapilio-kit#185]
### Short Description

When I have a video to upload, I would like to be able to process it and then manually review the output images before uploading.  It would be helpful to have a separate "Process" command which samples images from a video and geotags them, but does not upload them which the "Upload" command does.

### Feature Use case

Manually reviewing processed footage before uploading.

**Comment by bonj4** [comment]
# Mapilio Image Processing Guide

This document outlines the process of extracting, processing, and uploading images from video content using Mapilio Kit.

## Steps

### 1. Extract Images from Video

First, use the `Sampler` command to extract individual frames from your video:

```bash
mapilio_kit Sampler "/path/to/videos/video.MP4"
```

This command will create a series of image files from your video.

### 2. Process Extracted Images

Next, process the extracted images to gather metadata and additional information:

```bash
mapilio_kit decompose "path/to/videos/mapilio_sampled_video_frames/video.MP4"
```

This command generates a `mapilio_image_description.json` file containing detailed information about your processed images. You can review this file to verify the extracted data.

### 3. Upload Processed Images

Finally, upload your processed images to Mapilio:

```bash
mapilio_kit upload "/path/to/videos/mapilio_sampled_video_frames/video.MP4" --processed
```

## Notes
- Ensure all paths are correctly specified according to your system's file structure
- Verify that Mapilio Kit is properly installed before running these commands
- The `--processed` flag in the upload command indicates that the images have already been processed

For additional information or troubleshooting, please refer to the official Mapilio documentation.

**Comment by bonj4** [comment]
please use mapilio-kit v3.0.1
