### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mnalis** [mapilio/mapilio-kit#69]
Could you please add the copyright license to the GitHub repo?

**Comment by ozcan-durak** [comment]
Certainly, @gorkemgul,

Please take note of this and proceed with the update at your earliest convenience.

**Comment by gorkemgul** [comment]
Hi @mnalis,

License added to our repository. Indeed, to see the latest news about Mapilio or to report any kind of problems, you may join to our discord community from here: [Mapilio](https://discord.gg/VbUEdQWu)
