### ISSUE TITLE
Upload problem

### ISSUE THREAD

**Issue by avi3232** [mapilio/mapilio-kit#74]
Hi! Can't upload photos for a last 12 hours.

![image](https://github.com/mapilio/mapilio-kit/assets/91157543/97da65bc-d028-41de-b450-9b8b4921c884)

**Comment by gorkemgul** [comment]
Hi @avi3232,

It might be a temporary problem, would you please try to upload your photos again? 
For most recent information you may join to our discord community from here: [Mapilio](https://discord.gg/VbUEdQWu)

Best Regards,
