### ISSUE TITLE
Why processing (decompose) on Windows 10 so slow?

### ISSUE THREAD

**Issue by avi3232** [mapilio/mapilio-kit#97]
### Question

Mapilio-Kit v2 on Windiws 10 - proccesing for 5000 files is about 1 file per second. Same PC with Mapilio-Kit v2 on Ubuntu gives processing speed - 6-7 files per second. Why so big difference? PC is fast enough - i7 and SSD, 16gb ram.

**Comment by gorkemgul** [comment]
Hi @avi3232,

We took a test dataset and tested the process on both systems. We saw the time difference as well. For now, we don't know what actually causes to time difference, however, we're going to be working on it, to be able to understand what causes this effect. During this time you may help us to find it if you can find the source. 

Sincerely
